<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-56NTT3S9" failures="1" tests="3" name="Test" time="42.84" errors="0" timestamp="2024-03-13T22:16:45 IST">
  <testcase classname="Login_Functionality.LoginTest" name="Login" time="17.978"/>
  <testcase classname="Login_Functionality.LoginTest" name="BalanceCheck" time="7.291"/>
  <testcase classname="Login_Functionality.LoginTest" name="Deposit" time="15.534">
    <failure type="java.lang.AssertionError" message="expected [Deposit Successful] but found []">
      <![CDATA[java.lang.AssertionError: expected [Deposit Successful] but found []
at Login_Functionality.LoginTest.Deposit(LoginTest.java:99)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Deposit -->
</testsuite> <!-- Test -->
